# Generated by Django 4.2.3 on 2023-08-01 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='telephone',
        ),
    ]
