# Generated by Django 4.2.3 on 2023-08-01 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth_user', '0002_remove_profile_telephone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='auth_token',
        ),
    ]
