# Generated by Django 4.2.3 on 2023-08-01 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_auth_user', '0003_remove_profile_auth_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='was_invited',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invinting', to=settings.AUTH_USER_MODEL)),
                ('inviting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
